import {
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { id, timestamps } from "./columns";
import { tiktokAccounts } from "./tiktok-accounts";

/**
 * One row per finished TikTok LIVE session, summarized. Pulled from the managed
 * vendor by `syncTikTokLive()`. Idempotent on (accountId, externalSessionId).
 * Diamonds/gifts intentionally omitted (irrelevant to loan marketing — easy to
 * add later). Intra-session time-series snapshots are a future table.
 */
export const tiktokLiveSessions = pgTable(
  "tiktok_live_sessions",
  {
    id: id(),
    accountId: uuid("account_id")
      .notNull()
      .references(() => tiktokAccounts.id, { onDelete: "cascade" }),
    // Vendor/room id for this live — the idempotency key per account.
    externalSessionId: text("external_session_id").notNull(),
    title: text("title"),
    startedAt: timestamp("started_at", { withTimezone: true }),
    endedAt: timestamp("ended_at", { withTimezone: true }),
    durationSeconds: integer("duration_seconds").notNull().default(0),
    peakViewers: integer("peak_viewers").notNull().default(0),
    avgViewers: integer("avg_viewers").notNull().default(0),
    totalViews: integer("total_views").notNull().default(0),
    totalLikes: integer("total_likes").notNull().default(0),
    totalComments: integer("total_comments").notNull().default(0),
    totalShares: integer("total_shares").notNull().default(0),
    newFollowers: integer("new_followers"),
    // ── Manually entered from the TikTok creator backend — the TikTok-only
    // metrics the public connector can't capture (no live-analytics API exists).
    // Null = not entered. Admins fill these on the session page after a live. ──
    uniqueViewers: integer("unique_viewers"),
    activeViewers: integer("active_viewers"),
    avgWatchSeconds: integer("avg_watch_seconds"),
    directMessages: integer("direct_messages"),
    serviceBioViews: integer("service_bio_views"),
    interestedViewers: integer("interested_viewers"),
    diamonds: integer("diamonds"),
    // Denormalized count of unique viewers who commented a lead keyword (= leads
    // generated by this live). Detail rows live in `tiktok_live_leads`.
    keywordLeads: integer("keyword_leads").notNull().default(0),
    rawPayload: jsonb("raw_payload"),
    ...timestamps(),
  },
  (t) => ({
    uq: uniqueIndex("tiktok_live_sessions_uq").on(
      t.accountId,
      t.externalSessionId
    ),
    acctStartedIdx: index("tiktok_live_sessions_acct_started_idx").on(
      t.accountId,
      t.startedAt
    ),
  })
);
